version: "3.9"
services:
  sdcc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sdcc_container
    working_dir: /workspace
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
